"""empty message

Revision ID: 10643614830b
Revises: c8816d84c71d
Create Date: 2021-12-27 21:19:11.787948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10643614830b'
down_revision = 'c8816d84c71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invited', sa.Column('invite_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invited', 'invite_status')
    # ### end Alembic commands ###
